#!/usr/bin/expect -f
#

set timeout 5
# Allow ssh-rsa key types regardless of actual key type used, because it makes the script simpler
spawn sshpass -p foobar ssh -F /dev/null -o "HostKeyAlgorithms +ssh-rsa" -o PubkeyAuthentication=no -o IdentityAgent=none -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l $::env(USERNAME) $::env(NSO_IP)
expect {
    -re "connected from.*using ssh" { send -- "exit\r" }
    timeout { exit 1 }
}
expect eof
# wait for telnet to quit
wait
